package com.xworkz.overloading.conceptOverloading;

public class PetrolBunk {

	         //instance variables/states/properties/fields
	             public int id;
	             public String name;
	             public String location;
	             public String workerNames[] = new String[7];
	
	        // default constructor
	             public PetrolBunk() {
	            	 
	            	System.out.println("Petrolbunk constructor is created"); 
	            	 
	             }
	             
	          // parameterized constructor   
	             public PetrolBunk(int id,String name,String location,String[] workersName) {
	            	
	            	 // below statement is used for Constructor chaining 
	            	this();
	            	System.out.println("Calling parameterized constructor");
	            	this.id = id;
	            	this.name = name;
	            	this.location = location;
	            	this.workerNames = workersName;
	            	
	            	
	              }
	     
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	             
	
	
	
	
	
	
	
	
	
	
	
}
